<MainWindow>:
    id: main_win
    orientation: 'vertical'
    spacing: 10
    space_x: self.size[0]/3

    ScreenManager:
        id:screen_manager_main

        Screen:
            id: gestme_screen
            name: 'gestme_screen'

        Screen:
            id: login_screen
            name: 'login_screen'
        
        Screen:
            id: signup_screen
            name: 'signup_screen'